# -*- coding: utf-8 -*-
"""HeartRisk-ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tA9RS99pziPT0X_Ig6Cr5OwAkzNh6q1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split,cross_val_score, GridSearchCV
from sklearn.svm import SVC, LinearSVC

import keras
from keras.models import Sequential

df= pd.read_csv("cleaned_cardio.csv")
df



from matplotlib import rcParams
rcParams['figure.figsize'] = 11, 8
df['years'] = (df['age'] / 365).round().astype('int')
sns.countplot(x='years', hue='cardio', data = df, palette="Set2")

"""The graph shows that as the age increases of the person the risk of having a cardio-vascular disease increases

```
`# This is formatted as code`
```


"""

df_categorical = df.loc[:,['cholesterol','gluc', 'smoke', 'alco', 'active']]
sns.countplot(x="variable", hue="value",data= pd.melt(df_categorical))

"""**Cleaning of the Data**"""

df.isnull().values.any()
df.describe()

df.drop(df[(df['height'] > df['height'].quantile(0.975)) | (df['height'] < df['height'].quantile(0.025))].index,inplace=True)
df.drop(df[(df['weight'] > df['weight'].quantile(0.975)) | (df['weight'] < df['weight'].quantile(0.025))].index,inplace=True)

print("Diastilic pressure is higher than systolic one in {0} cases".format(df[df['ap_lo']> df['ap_hi']].shape[0]))

df.drop(df[(df['ap_hi'] > df['ap_hi'].quantile(0.975)) | (df['ap_hi'] < df['ap_hi'].quantile(0.025))].index,inplace=True)
df.drop(df[(df['ap_lo'] > df['ap_lo'].quantile(0.975)) | (df['ap_lo'] < df['ap_lo'].quantile(0.025))].index,inplace=True)

df.dropna()
df

df_sampled = df.sample(frac=0.8, random_state=42)
df_remaining = df.drop(df_sampled.index)
df

frac_to_drop = 0.7 + (0.1 * np.random.rand())  # Randomly choose a value between 70% and 80%
df_remaining = df.sample(frac=1-frac_to_drop, random_state=42)

df

df["age"] = df["years"]
df

df.drop("years",axis = 1)

df

df.rename(columns = {'cardio':'Target'}, inplace = True)
df

df.tail()

df.drop('years',axis =1,inplace =True)
df

Y = df.Target
X = df.drop('Target', axis=1)
X
Y

df.describe()

train, test, target, target_test = train_test_split(X,Y,test_size = 0.2,stratify=Y,random_state=2)

train.drop

df

sns.boxplot(x='Target', y='age', data=df)
plt.title('Plot between the Outcome and Age')
plt.show()

plt.figure(figsize=(8, 6))
sns.histplot(df['age'], bins=30, kde=True)
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

plt.subplot(1, 2, 2)
gluc_counts = df['gluc'].value_counts()
plt.pie(gluc_counts, labels=gluc_counts.index, autopct='%1.1f%%', colors=['lightgreen','lightblue', 'lightcoral'])
plt.title('Glucose Level Distribution')

plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""Pair Plot to show the relation betwwen each column"""

sns.pairplot(data=df, hue="gender", diag_kind="kde", palette="husl")
plt.title("Iris Dataset Pair Plot")
plt.show()

train, test, target, target_test = train_test_split(X,Y,test_size = 0.2,stratify=Y,random_state=2)

train.drop

Xtrain, Xval, Ztrain, Zval = train_test_split(train, target, test_size=0.2, random_state=0)

"""**Model training**
Logistic Regression
"""

logreg = LogisticRegression()
logreg.fit(train, target)
acc_log = round(logreg.score(train, target) * 100, 2)
acc_log

acc_test_log = round(logreg.score(test, target_test) * 100, 2)
acc_test_log

coeff_df = pd.DataFrame(train.columns.delete(0))
coeff_df.columns = ['Feature']
coeff_df["Correlation"] = pd.Series(logreg.coef_[0])
coeff_df.sort_values(by='Correlation', ascending=False)

"""**Predictive Model**-Random Forest"""

random_forest = GridSearchCV(estimator=RandomForestClassifier(), param_grid={'n_estimators': [100, 300]}, cv=5).fit(train, target)
random_forest.fit(train, target)
acc_random_forest = round(random_forest.score(train, target) * 100, 2)
print(acc_random_forest,random_forest.best_params_)

acc_test_random_forest = round(random_forest.score(test, target_test) * 100, 2)
acc_test_random_forest

"""Training and Testing scores of Logistic Regression and Random Forest"""

models = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', ],

    'Score_train': [acc_log,    acc_random_forest],

    'Score_test': [acc_test_log, acc_test_random_forest, ]
})

models



"""Input of the data that is to be predicted"""

input_data = []
name = input("Enter your name: ")
id = int(input("Enter id number of person: "))
age = int(input("Enter age of person: "))
gender = int(input("Enter gender of person {for male : 1 ; for female : 2}:  "))
height = int(input("Enter height of person in cm: "))
weight = int(input("Enter weight of person in kgs: "))
systolic = int(input("Enter systolic blood pressure of person in mmHg: "))
diastolic = int(input("Enter diastolic blood pressure of person in mmHg: "))
cholesterol = int(input("Enter cholesterol of person in level:1 to 3: "))
glucose = int(input("Enter glucose level of person in level:1 to 3:: "))
smoker = int(input("Does the person smoke? {Yes: 1; No: 0}: "))
alcoholic = int(input("Is the person alcoholic? {Yes: 1; No: 0}: "))
physically_fit = int(input("Is the person physically active? {Yes: 1; No: 0}: "))

input_data.append(id)
input_data.append(age)
input_data.append(gender)
input_data.append(height)
input_data.append(weight)
input_data.append(systolic)
input_data.append(diastolic)
input_data.append(cholesterol)
input_data.append(glucose)
input_data.append(smoker)
input_data.append(alcoholic)
input_data.append(physically_fit)

id = input_data[0]
age = input_data[1]
gender = input_data[2]
height = input_data[3]
weight = input_data[4]
systolic = input_data[5]
diastolic = input_data[6]
cholesterol = input_data[7]
glucose = input_data[8]
smoker = input_data[9]
alcoholic = input_data[10]
physically_fit = input_data[11]

input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

print(" *** WELCOME TO HEART DISEASE PREDICTOR ***")
print("-----------------------------------------------------")
print("Name of person: ",name)
print("-----------------------------------------------------")
print("id: ", id)
print("-----------------------------------------------------")
print("age:" , age)
print("-----------------------------------------------------")
if gender ==1:
    print("gender: male")
else:
    print("gender: female")
print("-----------------------------------------------------")
print("weight: ", weight)
print("-----------------------------------------------------")
print("systolic blood pressure: ", systolic)
print("-----------------------------------------------------")
print("diastolic blood pressure: ", diastolic)
print("-----------------------------------------------------")
print("cholesterol: ", cholesterol)
print("-----------------------------------------------------")
print("blood glucose level: ", glucose)
print("-----------------------------------------------------")

if smoker == 1:
  print("is he/she a smoker?: yes")
else:
  print("is he/she a smoker?: no")
print("-----------------------------------------------------")
if smoker == 1:
  print("is he/she a alcoholic?: yes")
else:
  print("is he/she a alcoholic?: no")

print("-----------------------------------------------------")
if physically_fit ==1:
  print("does he/she do any physical activity?: yes")
else:
  print("does he/she do any physical activity?: no")
print("-----------------------------------------------------")

import math

score = 0

if age >= 40:
  score += 1
elif age >= 50:
  score += 2

if gender == 1:
  score += 2
else:
  score += 1

h = height/100
bmi = weight / (h*h)

if bmi >= 40:
  score += 2
elif bmi >= 30:
  score += 1

if systolic in range(130,140) and diastolic in range(80,90):
  score += 1
elif systolic >= 140 and diastolic >= 90:
  score += 2

score += (cholesterol + glucose + smoker + alcoholic + physically_fit)

percentage = (score/16)*100

prediction = random_forest.predict(input_data_reshaped)

if (prediction[0] == 0):
    print('Person does not have heart disease.')
else:
    print('Person may have or may develop a heart disease in the future if this lifestyle is continued.')
print("-----------------------------------------------------")
print("Chances of cardiovascular disease: ", math.ceil(percentage*100)/100, "%")
print("-----------------------------------------------------")